'use strict';
const E=ChemEngine,Q=ChemPrecision,$=id=>document.getElementById(id);let topic='all',state={},result,precision={};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number.isFinite(x)?Number(x.toPrecision(7)).toString():'';
const group=()=>{let g=E.groups[topic];if(topic==='all'&&current().approximate)return {...g,eqs:[...g.eqs,{label:'Dilute-solution approximation: solvent volume ≈ solution volume',forms:{solution_solventVolume:'solution_V',solution_V:'solution_solventVolume'}}]};return g;};
const current=()=>state[topic]||(state[topic]={inputs:{},selected:{}});
function unit(v){return current().selected[v.id]||Object.keys(E.units[v.type])[0];}
function formatted(id,x){let v=group().vars.find(v=>v.id===id),y=E.convert(x,unit(v),v.type,id,false);return $('sigfig').checked?Q.format(y,precision[id],unit(v),v.type,id):fmt(y);}
function displayed(id,x){let v=group().vars.find(v=>v.id===id);return formatted(id,x)+' '+unit(v);}
function render(){let g=group(),s=current();setupGoals();$('title').textContent=g.title;$('fields').innerHTML=g.vars.map(v=>`<div class="field" id="field-${v.id}"><label for="input-${v.id}">${esc(v.label)}</label><div class="symbol">${esc(v.id.replace(/^(nuclear|gas|solution|reaction)_/,''))}${v.hint?' · '+esc(v.hint):''}</div><div class="entry"><input type="text" inputmode="decimal" id="input-${v.id}" data-input="${v.id}" autocomplete="off" placeholder="Unknown" aria-label="${esc(v.label)}"><select data-unit="${v.id}" aria-label="Unit for ${esc(v.label)}">${Object.keys(E.units[v.type]).map(u=>`<option ${unit(v)===u?'selected':''}>${esc(u)}</option>`).join('')}</select></div><div class="field-bottom"><span class="badge"></span><label class="exact-label"><input type="checkbox" data-exact="${v.id}" ${s.exact?.[v.id]?'checked':''}> Exact</label><span><button class="clear" data-clear="${v.id}" hidden>Clear</button><button class="trail-button" data-trail="${v.id}" hidden>Show calculation ↗</button></span></div></div>`).join('');$('equations').innerHTML=g.eqs.map(e=>`<div class="equation">${esc(e.label)}</div>`).join('');update();}
function update(skip){const g=group(),s=current(),inputs={},inputPrecision={},invalid=[];for(const v of g.vars){if(s.inputs[v.id]!==undefined){let raw=s.inputs[v.id],x=Number(raw);if(!raw.trim()||!Number.isFinite(x)){invalid.push('Enter a valid number for '+v.label);continue;}x=s.precision?.[v.id]?.value??E.convert(x,unit(v),v.type,v.id);if(!E.valid(v.id,x,topic)){invalid.push('Value outside the allowed range for '+v.label);continue;}inputs[v.id]=x;inputPrecision[v.id]=s.exact?.[v.id]?{value:x,p:-Infinity}:s.precision?.[v.id]||Q.base(raw,unit(v),v.type,v.id);}}
const chemical=gatherChemistry(inputs,inputPrecision,invalid);result=E.solve(topic,inputs,group());result.inputIssues=invalid;precision=Q.propagate(result,inputPrecision);for(const [id,f] of Object.entries(chemical))result.trails[id]={deps:[],expr:'',label:'Molar mass of '+f.formula,formula:f};
for(const v of g.vars){let entered=s.inputs[v.id]!==undefined,known=result.values[v.id]!==undefined,derived=!entered&&known,el=$('field-'+v.id),input=$('input-'+v.id);el.className='field'+(entered?' user':derived?' calculated':'');if(skip!==v.id)input.value=entered?s.inputs[v.id]:known?formatted(v.id,result.values[v.id]):'';el.querySelector('.badge').textContent=entered?'Your input':derived?'Calculated':'Unknown';el.querySelector('.exact-label').hidden=!entered;input.setAttribute('aria-invalid',String(entered&&!Object.hasOwn(inputs,v.id)));el.querySelector('[data-trail]').hidden=!derived;el.querySelector('[data-clear]').hidden=!entered;}
const count=Object.keys(result.trails).length,issues=[...invalid,...result.issues];$('status').innerHTML=`<strong>${count}</strong> calculated · ${Object.keys(inputs).length} entered<p class="muted">${g.vars.length-Object.keys(result.values).length} values remain unknown</p>`+issues.map(x=>`<div class="issue">${esc(x)}</div>`).join('')+(issues.length?'':'<p>✓ No conflicts detected</p>');let seen=new Set(),suggestions=result.suggestions.filter(f=>{let key=f.target+f.missing.join(',');if(seen.has(key))return false;seen.add(key);return true;}).sort((a,b)=>{const related=f=>g.eqs.some(e=>Object.keys(e.forms).includes(f.target)&&Object.values(e.forms).some(expr=>E.parse(expr).deps.some(d=>Object.hasOwn(result.values,d))));return Number(related(b))-Number(related(a))||a.missing.length-b.missing.length;}).slice(0,6);const name=id=>g.vars.find(v=>v.id===id)?.label||id;$('suggestions').innerHTML=suggestions.length?suggestions.map(f=>`<div class="suggestion">Enter <b>${f.missing.map(x=>esc(name(x))).join(' + ')}</b> to calculate ${esc(name(f.target))}.</div>`).join(''):'<p class="muted">'+(g.vars.length?(Object.keys(result.values).length===g.vars.length?'All available variables are determined.':'Remaining values cannot be solved with these inputs; check for zero or degenerate relationships.'):'Apply your formulas to get started.')+'</p>';updateGoal();filterFields();}
$('fields').oninput=e=>{let id=e.target.dataset.input;if(!id)return;let val=e.target.value;if(current().precision)delete current().precision[id];if(val==='')delete current().inputs[id];else current().inputs[id]=val;update(id);};
$('fields').onchange=e=>{let exact=e.target.dataset.exact;if(exact){let s=current();s.exact||={};s.exact[exact]=e.target.checked;update();return;}let id=e.target.dataset.unit;if(!id)return;let s=current(),v=group().vars.find(v=>v.id===id),old=unit(v),next=e.target.value;if(s.inputs[id]!==undefined&&Number.isFinite(Number(s.inputs[id]))){const base=s.precision?.[id]?.value??E.convert(Number(s.inputs[id]),old,v.type,id);s.precision||={};s.precision[id]||=Q.base(s.inputs[id],old,v.type,id);s.inputs[id]=Q.format(E.convert(base,next,v.type,id,false),s.precision[id],next,v.type,id);}s.selected[id]=next;update();};
$('fields').onclick=e=>{let id=e.target.dataset.clear;if(id){delete current().inputs[id];if(current().precision)delete current().precision[id];update();}id=e.target.dataset.trail;if(id){let seen=new Set(),html='';function walk(key){if(seen.has(key))return;seen.add(key);let t=result.trails[key];if(!t){html+=`<p><b>${esc(key)}</b> = ${esc(displayed(key,result.values[key]))} <span class="muted">(your input)</span></p>`;return;}if(t.formula){html+="<div class='step'><b>"+esc(t.label)+" = "+esc(displayed(key,result.values[key]))+"</b><p>"+esc(t.formula.terms.join(' + '))+"</p><p class='muted'>CIAAW abridged atomic weights (2024); integer atom counts.</p></div>";return;}t.deps.forEach(walk);html+=`<div class="step"><b>${esc(key)} = ${esc(displayed(key,result.values[key]))}</b><p>${esc(t.label)}</p><code>${esc(t.expr)}</code><p class="muted">Using ${t.deps.map(d=>esc(d)+' = '+esc(displayed(d,result.values[d]))).join(', ')}</p></div>`;}walk(id);$('trailBody').innerHTML=html+'<p class="muted">Expressions above use canonical units internally: seconds, kelvin, liters, atmospheres, moles, grams, and joules per mole.</p>';$('trail').showModal();}};
$('close').onclick=()=>$('trail').close();$('reset').onclick=()=>{state[topic]={inputs:{},selected:{}};render();};
const examples={all:{inputs:{solution_mass:'5.844',solution_M:'58.44',solution_V:'500.0',solution_solvent:'495.0',solution_i:'2',solution_T:'25.00',solution_Kf:'1.86',solution_Kb:'0.512',solution_freeze0:'0.00',solution_boil0:'100.00'},selected:{solution_V:'mL',solution_T:'°C',solution_freeze0:'°C',solution_freeze:'°C',solution_boil0:'°C',solution_boil:'°C'},exact:{solution_i:true}},decay:{inputs:{half:'5.27',initial:'20',t:'10'},selected:{half:'yr',t:'yr',k:'yr⁻¹'}},kinetics:{inputs:{half:'120',initial:'0.5',t:'240'}},arrhenius:{inputs:{k1:'0.01',T1:'298.15',T2:'318.15',Ea:'50'},selected:{Ea:'kJ/mol'}},gas:{inputs:{P:'1',V:'22.414',T:'273.15',M:'28.014'}},solutions:{inputs:{mass:'5.844',M:'58.44',V:'500',V2:'1',solvent:'495'},selected:{V:'mL'}},colligative:{inputs:{i:'2',b:'0.1',Kf:'1.86',Kb:'0.512',freeze0:'0',boil0:'100'},selected:{freeze0:'°C',freeze:'°C',boil0:'°C',boil:'°C'}},osmotic:{inputs:{i:'1',mass:'1',M:'180.16',V:'0.1',T:'25'},selected:{T:'°C'}}};
$('example').onclick=()=>{state[topic]=JSON.parse(JSON.stringify(examples[topic]));state[topic].selected||={};render();};
// Initial render occurs after target and chemistry helpers load.


function filterFields(){let query=$('search').value.toLowerCase().trim(),g=group(),s=current(),visibleIds=new Set([...Object.keys(result.values),...(s.added||[])]);if(s.target)visibleIds.add(s.target);if(s.focus)s.focus.forEach(id=>visibleIds.add(id));else if(s.target&&answerPlans.length)answerPlans[0].missing.forEach(id=>visibleIds.add(id));let count=0;for(const v of g.vars){const matches=(v.label+' '+v.id+' '+(v.context||'')).toLowerCase().includes(query);const visible=query?matches:!$('relevant').checked||visibleIds.has(v.id);$('field-'+v.id).hidden=!visible;if(visible)count++;}$('empty').hidden=count>0;}
$('search').oninput=()=>{current().focus=null;filterFields();};$('relevant').onchange=()=>{current().focus=null;filterFields();};$('sigfig').onchange=()=>update();



