/* Supplementary input bases for the 80 authored systems. Dimensionless entries are explicit. */
const CatalogueInputUnits=[
'B=m³/mol',
'Mheavy=kg/mol|Mlight=kg/mol|v=m/s|Cv=J/(mol·K)',
'soluteVolume=L|totalVolume=L|molarMass=g/mol|electrons=eq/mol',
'extractions=extractions',
'betC=1|relativeP=1|monolayer=mol|adsorptionRate=Pa⁻¹·s⁻¹|desorptionRate=s⁻¹|excessMoles=mol',
'gammaA=1|gammaB=1|osmoticPressure=Pa|totalIonConc=mol/m³|lambdaA=S·m²/mol|cSIa=mol/m³|lambdaB=S·m²/mol|cSIb=mol/m³',
'kA=s⁻¹|kB=s⁻¹|forwardK=s⁻¹|reverseK=s⁻¹',
'gamma=1|gOverT1=J/(mol·K)|reactionH=J/mol|K1=1|vaporP1=Pa|vaporH=J/mol',
'signal=signal units|intercept=signal units|slope=signal/(mol/L)|kB=1|kA=1|retentionB=s|retentionA=s|halfWidth=s|columnLength=m',
'massA=kg|massB=kg',
'',
'particleDensity=kg/m³',
'innerRadius=m|outerRadius=m',
'innerRadius=m|outerRadius=m|width=m|length=m|inertia=kg·m²|massA=kg|massB=kg',
'phase=rad|initialEnergy=J',
'sourceSpeed=m/s|observerSpeed=m/s',
'radius1=m|radius2=m|n2=1|n1=1|initialIntensity=W/m²|angle=rad|order=integer order|spacing=m',
'primaryV=V|secondaryTurns=turns|primaryTurns=turns',
'u=m/s|x=m|t=s',
'grossCounts=counts|grossTime=s|backgroundCounts=counts|backgroundTime=s|measuredRate=s⁻¹|deadTime=s|nucleons=nucleons',
'membraneArea=m²|thickness=m',
'flow=L/h|workingVolume=L|biomassIncrease=g|substrateConsumed=g|maintenance=g/(g·h)',
'KiPrime=mol/L|totalReceptor=mol/L|T=K|standardConc=mol/L',
'initialCopies=copies|controlDeltaCt=cycles|abs260=1|abs280=1|dilutionFactor=1',
'sumAgeContribution=years·offspring/initial individual|netReproduction=offspring/initial individual|population=individuals',
'largestSpeciesCount=individuals|regionalRichness=species|meanLocalRichness=species|coefficient=species/m²^exponent|habitatArea=m²|exponent=1|richnessB=species|richnessA=species|areaB=m²|areaA=m²',
'protonFlux=mol/s|protonsPerATP=mol/mol|standardG=J/mol|T=K|adpActivity=1|phosphateActivity=1|atpActivity=1|carbonDioxide=mol|oxygenConsumed=mol|energyReleased=J',
'systolic=mmHg|diastolic=mmHg|inspiratoryReserve=mL|expiratoryReserve=mL|residualVolume=mL|carbonDioxideOutput=mL/min|oxygenUptake=mL/min',
'voltageSlope=V/s|PK=relative permeability|Ko=mol/L|PNa=relative permeability|Nao=mol/L|PCl=relative permeability|Cli=mol/L|Ki=mol/L|Nai=mol/L|Clo=mol/L|radius=m|membraneSpecificResistance=Ω·m²|axialResistivity=Ω·m|initialVoltage=V|distance=m',
'observedDouble=individuals|expectedDouble=individuals',
'deferral=periods|targetFV=currency units',
'finalBalloon=currency units|propertyValue=currency units|monthlySaving=currency units/month|netOperatingIncome=currency units/year|annualDebtService=currency units/year',
'frequency=periods/year|annualCouponRate=decimal/year|days=days|elapsedDays=days|couponDays=days|clean=currency units|weightedPV=currency units·years|annualYield=decimal/year',
'weightA=1|durationA=years|durationB=years|spotRate=decimal/year|time=years|spotLong=decimal/year|longTime=years|spotShort=decimal/year|shortTime=years|discountLong=1|discountShort=1|valueA=currency units|valueB=currency units',
'betaA=1|betaB=1|marketReturn=decimal/period|benchmarkReturn=decimal/period|trackingError=decimal/period',
'terminalValue=currency units/share|payout=1|ROE=decimal/year|totalDividends=currency units|shares=shares|equityValue=currency units|debtValue=currency units|preferredValue=currency units|minorityInterest=currency units|cash=currency units',
'netMargin=1|EBIT=currency units/year|interestExpense=currency units/year',
'currentAssets=currency units|currentLiabilities=currency units|capex=currency units/year|changeNWC=currency units/year|netIncome=currency units/year|netBorrowing=currency units/year|equityMarketValue=currency units|investedCapital=currency units|costOfCapital=decimal/year',
'grossIncome=currency units|taxRate=decimal|taxFreeYield=decimal/year|salePrice=currency units|costBasis=currency units|capitalGainTax=decimal|currentPrice=currency units|periodReturnA=decimal/period|periodReturnB=decimal/period',
'annualCash=currency units/year|unitsUsed=units/year|lifetimeUnits=units|annualProfit=currency units/year',
'',
'',
'',
'lambdaA=expected events|lambdaB=expected events',
'upper=data units|lower=data units',
'',
'failures=failures',
'nullSlope=response/predictor',
'population=observations|df=degrees of freedom|oldN=observations|newN=observations',
'',
'vertices=vertices|apothem=m',
'majorRadius=m|minorRadius=m',
'A=1|B=1|C=coordinate units|ratio=1|centerX=coordinate units|centerY=coordinate units|radius=coordinate units',
'',
'firstReciprocal=value units⁻¹|reciprocalDifference=value units⁻¹/step',
'semiLatus=coordinate units|eccentricity=1|initialRadius=coordinate units|growth=coordinate units/rad',
'',
'',
'fPlus=y units|fMinus=y units|fCenter=y units|x=x units|xB=x units|fB=y units|xA=x units|fA=y units|maxSecond=y/x² units|panels=panels',
'secondReal=1|secondImaginary=1',
'',
'',
'Q2=quantity units|Q1=quantity units|income2=currency|income1=currency|otherPrice2=currency/unit|otherPrice1=currency/unit|slope=currency/unit²|scale=model-specific|elasticity=1',
'',
'outputPrice=currency/output',
'price=currency/unit|elasticity=1|shareA=1|shareB=1|shareC=1|firms=firms',
'programCost=currency|unitsAvoided=units|discountedBenefits=currency|discountedCosts=currency',
'marginalImport=1|taxRate=1',
'hoursWorked=hours/year|GDP=currency/year|netFactorIncome=currency/year|populationGrowth=year⁻¹|capitalPerWorker=currency/worker|growthPercent=percent/year',
'domesticInflation=decimal/year|foreignInflation=decimal/year|domesticRate=decimal/period|foreignRate=decimal/period|moneyIncrease=currency|inflationRate=decimal/year|foreignAmount=foreign currency',
'runoffCoefficient=1|flowA=m³/s|concA=kg/m³|flowB=m³/s|concB=kg/m³|initialConcentration=kg/m³|finalConcentration=kg/m³',
'solidsConcentration=kg/m³|reactorSolids=kg|wastedSolidsRate=kg/s|disinfectantConcentration=mg/L|contactMinutes=min',
'sedimentRate=mg/(m²·day)|bedArea=m²|ammoniaNitrogen=mg N/L|equivalentsPerLiter=eq/L',
'massConcentration=mg/m³|initial=mg/m³|time=s|emissionMass=kg|fuelMass=kg|stackFlow=m³/s|stackConcentration=mg/m³|operatingSeconds=s/year',
'output=output units|savedElectricity=kWh|electricMJ=MJ|heatMJ=MJ|fuelMJ=MJ',
'radius=m|ratedWatts=W|massFlow=kg/s|specificHeat=J/(kg·K)|temperatureRise=K',
'availableVolume=m³|recoveredMass=kg|inputMass=kg|contaminantMass=kg|substitutionFactor=1',
'finalStock=tonnes C|initialStock=tonnes C|gasMass=tonnes|perHectareRate=tonnes C/(ha·year)|emittedCarbonPerYear=tonnes C/year|finalBiomass=tonnes dry biomass|initialBiomass=tonnes dry biomass|ppmIncrement=ppm',
'waterDensity=g/cm³|fieldCapacity=cm³/cm³|wiltingPoint=cm³/cm³|rootDepth=mm|treatedLoss=soil loss units|untreatedLoss=soil loss units|depth=m|bulkDensitySI=kg/m³|carbonFraction=1|deliveredSediment=tonnes|erodedSoil=tonnes',
'years=years|tissueConcentration=mg/kg|waterConcentration=mg/L|predatorConcentration=mg/kg|preyConcentration=mg/kg|remainingArea=m²|originalArea=m²|areaExponent=1'
];
if(typeof module!=='undefined')module.exports=CatalogueInputUnits;
