/* Data/function helpers feed aggregate quantities into the same solver. */
const originalGatherChemistry=gatherChemistry;
const dataDerivations={sample_n:'Count observations',sample_sum:'Sum observations',sample_mean:'Sum observations / number of observations',sample_ss:'Sum (observation − mean)²',sample_s:'sqrt(sum squared deviations / (n−1))',sample_min:'Minimum observation',sample_max:'Maximum observation',sample_median:'Middle sorted observation, or mean of the two middle observations',sample_mode:'Unique most frequent observation',regression_b:'Sum (x−mean x)(y−mean y) / sum (x−mean x)²',regression_a:'Mean y − slope × mean x',regression_r:'Sum cross deviations / sqrt(sum x squared deviations × sum y squared deviations)',chisquare_chi:'Sum (observed − expected)² / expected',diversity_index:'1 − sum (species count / total count)²',distribution_mean:'Sum outcome × probability',distribution_sd:'sqrt(sum (outcome − expected value)² × probability)',function_value:'Substitute x into the entered expression',function_derivative:'Richardson-extrapolated central difference (numeric approximation)',function_second:'Second central difference (numeric approximation)',function_integral:'Composite Simpson integration, refined until convergence (numeric approximation)'};
gatherChemistry=function(inputs,p,invalid){const sources=originalGatherChemistry(inputs,p,invalid),s=current(),T=CalcTools;
function add(values,label){for(const [id,value]of Object.entries(values)){if(!Number.isFinite(value))throw Error('The data produced an undefined or overflowing result.');if(inputs[id]!==undefined){if(Math.abs(inputs[id]-value)>1e-6+1e-3*Math.max(Math.abs(value),Math.abs(inputs[id])))invalid.push('Entered '+(group().vars.find(v=>v.id===id)?.label||id)+' conflicts with '+label+'.');}else{inputs[id]=value;p[id]={value,p:Math.floor(Math.log10(Math.abs(value)||1))-6};sources[id]={formula:label,terms:[dataDerivations[id]||label],dataset:true,counts:{},precision:p[id]};}}}
$('dataInfo').textContent='';if(s.data?.x?.trim()){try{const x=T.list(s.data.x),y=T.list(s.data.y||''),mode=s.data.mode||'sample';const values=mode==='chi'?T.chi(x,y):mode==='diversity'?T.diversity(x):mode==='distribution'?T.distribution(x,y):T.sample(x,y);add(values,'Data calculation ('+mode+'), '+x.length+' entries');$('dataInfo').textContent='Calculated '+Object.keys(values).length+' quantities. Statistics use numeric precision, not significant-figure rules.';}catch(e){invalid.push('Data: '+e.message);$('dataInfo').textContent=e.message;}}
$('functionInfo').textContent='';if(s.math?.expr?.trim()){const m=s.math,messages=[];if(m.point?.trim()){try{const x=Number(m.point);if(!Number.isFinite(x))throw Error('Enter a valid evaluation point.');add(T.at(m.expr,x),'Numeric evaluation of '+m.expr+' at x='+x);messages.push('Value and derivatives calculated.');}catch(e){invalid.push('Function: '+e.message);messages.push(e.message);}}if(m.a?.trim()&&m.b?.trim()){try{const a=Number(m.a),b=Number(m.b);if(!Number.isFinite(a)||!Number.isFinite(b))throw Error('Enter valid integral bounds.');add(T.integral(m.expr,a,b),'Numerical integral of '+m.expr+' from '+a+' to '+b);messages.push('Definite integral calculated.');}catch(e){invalid.push('Integral: '+e.message);messages.push(e.message);}}$('functionInfo').textContent=messages.join(' ')||'Enter an evaluation point or both integration bounds.';}return sources;};
const beforeDataSetup=setupGoals;
setupGoals=function(){beforeDataSetup();const s=current();$('dataMode').value=s.data?.mode||'sample';$('dataX').value=s.data?.x||'';$('dataY').value=s.data?.y||'';for(const [id,key]of[['mathExpression','expr'],['mathPoint','point'],['mathA','a'],['mathB','b']])$(id).value=s.math?.[key]||'';};
for(const [id,key]of[['dataX','x'],['dataY','y']])$(id).oninput=()=>{current().data||={};current().data[key]=$(id).value;update();};
$('dataMode').onchange=()=>{current().data||={};current().data.mode=$('dataMode').value;update();};
for(const [id,key]of[['mathExpression','expr'],['mathPoint','point'],['mathA','a'],['mathB','b']])$(id).oninput=()=>{current().math||={};current().math[key]=$(id).value;update();};
const beforeDataGoal=updateGoal;
updateGoal=function(){beforeDataGoal();const id=current().target||'';if(/^(function|sample|regression|chisquare|diversity|distribution)_/.test(id)&&result.values[id]===undefined){const tip='<p class="muted">'+(id.startsWith('function_')?'Enter a function and point or bounds to calculate this value.':'You can also enter a data set to calculate this quantity automatically.')+'</p><button data-open-tools="true">Open data & functions</button>';$('goalStatus').innerHTML=tip+$('goalStatus').innerHTML;}};
const beforeDataClick=$('goalStatus').onclick;
$('goalStatus').onclick=e=>{if(e.target.dataset.openTools){$('optionsPanel').open=true;$('dataTools').open=true;$('dataTools').scrollIntoView?.({behavior:'smooth',block:'start'});}else beforeDataClick(e);};
render();
