/* Canonical units: seconds, kelvin, liters, atmospheres, moles, grams, joules. */
(function(root){
'use strict';
const R=8.314462618, Ra=0.082057366;
const units={time:{s:1,min:60,h:3600,day:86400,yr:31557600},rate:{'s⁻¹':1,'min⁻¹':1/60,'h⁻¹':1/3600,'yr⁻¹':1/31557600},mass:{g:1,kg:1000,mg:.001},volume:{L:1,mL:.001,'m³':1000},pressure:{atm:1,kPa:1/101.325,Pa:1/101325,bar:1/1.01325,mmHg:1/760},energy:{'J/mol':1,'kJ/mol':1000},temp:{K:1,'°C':1},amount:{mol:1,mmol:.001},concentration:{'mol/L':1,'mmol/L':.001},plain:{'—':1},percent:{'%':1},molarMass:{'g/mol':1},molality:{'mol/kg':1},constant:{'K·kg/mol':1}};
const v=(id,label,type='plain',hint='')=>({id,label,type,hint});
const eq=(label,forms)=>({label,forms});
const decay=[v('half','Half-life','time'),v('k','Rate constant','rate'),v('t','Elapsed time','time'),v('initial','Initial amount','mass'),v('remaining','Remaining amount','mass'),v('lost','Amount decayed','mass'),v('fraction','Fraction remaining'),v('percent','Percent remaining','percent'),v('halves','Elapsed half-lives')];
const decayE=[eq('k = ln(2) / half',{k:'ln(2)/half',half:'ln(2)/k'}),eq('fraction = exp(−k·t)',{fraction:'exp(-k*t)',k:'-ln(fraction)/t',t:'-ln(fraction)/k'}),eq('remaining = initial · fraction',{remaining:'initial*fraction',initial:'remaining/fraction',fraction:'remaining/initial'}),eq('lost = initial − remaining',{lost:'initial-remaining',initial:'lost+remaining',remaining:'initial-lost'}),eq('percent = 100 · fraction',{percent:'100*fraction',fraction:'percent/100'}),eq('halves = t / half',{halves:'t/half',t:'halves*half',half:'t/halves'})];
const groups={
decay:{title:'Nuclear decay',vars:decay,eqs:decayE},
kinetics:{title:'First-order kinetics',vars:[v('half','Half-life','time'),v('k','Rate constant','rate'),v('t','Reaction time','time'),v('initial','Initial concentration','concentration'),v('remaining','Final concentration','concentration'),v('fraction','Fraction remaining'),v('rate','Instantaneous rate','plain','mol/L/s')],eqs:[...decayE.slice(0,3),eq('rate = k · remaining',{rate:'k*remaining',k:'rate/remaining',remaining:'rate/k'})]},
arrhenius:{title:'Arrhenius',vars:[v('k1','Rate constant at T₁','rate'),v('k2','Rate constant at T₂','rate'),v('T1','Temperature T₁','temp'),v('T2','Temperature T₂','temp'),v('Ea','Activation energy','energy'),v('A','Pre-exponential factor','rate')],eqs:[eq('k₁ = A exp(−Ea / RT₁)',{k1:`A*exp(-Ea/(${R}*T1))`,A:`k1*exp(Ea/(${R}*T1))`,Ea:`-${R}*T1*ln(k1/A)`,T1:`-Ea/(${R}*ln(k1/A))`}),eq('k₂ = A exp(−Ea / RT₂)',{k2:`A*exp(-Ea/(${R}*T2))`,A:`k2*exp(Ea/(${R}*T2))`,Ea:`-${R}*T2*ln(k2/A)`,T2:`-Ea/(${R}*ln(k2/A))`}),eq('ln(k₂/k₁) = −Ea/R · (1/T₂ − 1/T₁)',{Ea:`-${R}*ln(k2/k1)/(1/T2-1/T1)`,k2:`k1*exp(-Ea/${R}*(1/T2-1/T1))`,k1:`k2*exp(Ea/${R}*(1/T2-1/T1))`,T2:`1/(1/T1-${R}/Ea*ln(k2/k1))`,T1:`1/(1/T2+${R}/Ea*ln(k2/k1))`})]},
gas:{title:'Gas laws',vars:[v('P','Pressure','pressure'),v('V','Volume','volume'),v('n','Amount','amount'),v('T','Temperature','temp'),v('mass','Mass','mass'),v('M','Molar mass','molarMass'),v('P2','Final pressure','pressure'),v('V2','Final volume','volume'),v('T2','Final temperature','temp')],eqs:[eq('PV = nRT',{P:`n*${Ra}*T/V`,V:`n*${Ra}*T/P`,n:`P*V/(${Ra}*T)`,T:`P*V/(n*${Ra})`}),eq('mass = n · M',{mass:'n*M',n:'mass/M',M:'mass/n'}),eq('P₁V₁/T₁ = P₂V₂/T₂ (fixed amount)',{P:'P2*V2*T/(T2*V)',V:'P2*V2*T/(T2*P)',T:'P*V*T2/(P2*V2)',P2:'P*V*T2/(T*V2)',V2:'P*V*T2/(T*P2)',T2:'P2*V2*T/(P*V)'})]},
solutions:{title:'Solutions & dilution',vars:[v('c','Molarity','concentration'),v('n','Solute amount','amount'),v('V','Solution volume','volume'),v('mass','Solute mass','mass'),v('M','Solute molar mass','molarMass'),v('c2','Diluted molarity','concentration'),v('V2','Diluted volume','volume'),v('solvent','Solvent mass','mass'),v('b','Molality','molality'),v('solventVolume','Solvent volume before mixing','volume'),v('solventDensity','Pure solvent density','density'),v('density','Solution density','density'),v('totalMass','Total solution mass','mass'),v('massPercent','Solute mass percent','percent')],eqs:[eq('n = c · V',{n:'c*V',c:'n/V',V:'n/c'}),eq('mass = n · M',{mass:'n*M',n:'mass/M',M:'mass/n'}),eq('c₁V₁ = c₂V₂',{c:'c2*V2/V',V:'c2*V2/c',c2:'c*V/V2',V2:'c*V/c2'}),eq('b = n / solvent(kg)',{b:'1000*n/solvent',n:'b*solvent/1000',solvent:'1000*n/b'}),eq('Solvent mass = solvent density × solvent volume',{solvent:'solventDensity*solventVolume',solventDensity:'solvent/solventVolume',solventVolume:'solvent/solventDensity'}),eq('Solution mass = solution density × solution volume',{totalMass:'density*V',density:'totalMass/V',V:'totalMass/density'}),eq('Solution mass = solute mass + solvent mass',{totalMass:'mass+solvent',mass:'totalMass-solvent',solvent:'totalMass-mass'}),eq('Solute mass % = 100 × solute mass / solution mass',{massPercent:'100*mass/totalMass',mass:'massPercent*totalMass/100',totalMass:'100*mass/massPercent'}),eq('Molality from molarity and solution density',{b:'1000*c/(density-c*M)',c:'b*density/(1000+b*M)',density:'1000*c/b+c*M',M:'(density-1000*c/b)/c'}),eq('Molality from solute mass percent',{b:'1000*massPercent/(M*(100-massPercent))',massPercent:'100*b*M/(1000+b*M)',M:'1000*massPercent/(b*(100-massPercent))'})]},
colligative:{title:'Colligative properties',vars:[v('i','van ’t Hoff factor'),v('b','Molality','molality'),v('Kf','Freezing-point constant','constant'),v('Kb','Boiling-point constant','constant'),v('df','Freezing-point depression','temp'),v('db','Boiling-point elevation','temp'),v('freeze0','Pure solvent freezing point','temp'),v('freeze','Solution freezing point','temp'),v('boil0','Pure solvent boiling point','temp'),v('boil','Solution boiling point','temp')],eqs:[eq('ΔTf = i Kf b',{df:'i*Kf*b',i:'df/(Kf*b)',Kf:'df/(i*b)',b:'df/(i*Kf)'}),eq('ΔTb = i Kb b',{db:'i*Kb*b',i:'db/(Kb*b)',Kb:'db/(i*b)',b:'db/(i*Kb)'}),eq('Tf = Tf° − ΔTf',{freeze:'freeze0-df',freeze0:'freeze+df',df:'freeze0-freeze'}),eq('Tb = Tb° + ΔTb',{boil:'boil0+db',boil0:'boil-db',db:'boil-boil0'})]},
osmotic:{title:'Osmotic pressure',vars:[v('osm','Osmotic pressure','pressure'),v('i','van ’t Hoff factor'),v('c','Molarity','concentration'),v('T','Temperature','temp'),v('n','Solute amount','amount'),v('V','Solution volume','volume'),v('mass','Solute mass','mass'),v('M','Molar mass','molarMass')],eqs:[eq('Π = i c RT',{osm:`i*c*${Ra}*T`,i:`osm/(c*${Ra}*T)`,c:`osm/(i*${Ra}*T)`,T:`osm/(i*c*${Ra})`}),eq('n = cV',{n:'c*V',c:'n/V',V:'n/c'}),eq('mass = nM',{mass:'n*M',n:'mass/M',M:'mass/n'})]},
custom:{title:'Custom formulas',vars:[],eqs:[]}};
// Small expression parser; never executes JavaScript or accesses global objects.
function parse(expr,values={}){const tokens=expr.match(/(?:\d*\.\d+|\d+\.?\d*)(?:[eE][+-]?\d+)?|[A-Za-z_]\w*|[()+\-*/^]/g)||[];if(tokens.join('')!==expr.replace(/\s/g,''))throw Error('Unsupported character');let p=0;const deps=new Set();function atom(){let t=tokens[p++];if(t==='+'||t==='-')return (t==='-'?-1:1)*atom();if(t==='('){let x=sum();if(tokens[p++]!==')')throw Error('Missing )');return x;}if(/^[0-9.]/.test(t||''))return Number(t);if(/^[A-Za-z_]/.test(t||'')){if(['ln','exp','sqrt','log','abs'].includes(t)&&tokens[p]==='('){p++;let x=sum();if(tokens[p++]!==')')throw Error('Missing )');return ({ln:Math.log,exp:Math.exp,sqrt:Math.sqrt,log:Math.log10,abs:Math.abs})[t](x);}if(t==='pi')return Math.PI;deps.add(t);return values[t]??NaN;}throw Error('Expected value');}function power(){let x=atom();if(tokens[p]==='^'){p++;x=Math.pow(x,power());}return x;}function product(){let x=power();while(['*','/'].includes(tokens[p])){let op=tokens[p++],y=power();x=op==='*'?x*y:x/y;}return x;}function sum(){let x=product();while(['+','-'].includes(tokens[p])){let op=tokens[p++],y=product();x=op==='+'?x+y:x-y;}return x;}let value=sum();if(p!==tokens.length)throw Error('Unexpected token');return {value,deps:[...deps]};}
function convert(value,unit,type,id,toBase=true){if(type==='temp'&&unit==='°C'&&!/(^|_)(df|db)$/.test(id))return value+(toBase?273.15:-273.15);return toBase?value*units[type][unit]:value/units[type][unit];}
function valid(id,x,group){if(!Number.isFinite(x))return false;if(group==='custom')return true;if(/^motion_(d|u|vf|a|v)$/.test(id)||/^(population|logistic)_r$/.test(id))return true;if(/^genetics_/.test(id)||id==='absorbance_transmission')return x>=0&&x<=1;id=id.replace(/^(nuclear|gas|solution|reaction)_/,'');if(['freeze','freeze0','boil','boil0'].includes(id))return x>=0;if(id==='fraction')return x>=0&&x<=1;if(id==='percent')return x>=0&&x<=100;return x>=0;}
function solve(group,inputs,custom){let g=custom||groups[group],values={...inputs},trails={},issues=[],seen=new Set();const forms=g.eqs.flatMap(e=>Object.entries(e.forms).map(([target,expr])=>({target,expr,label:e.label,deps:parse(expr).deps})));let changed=true;while(changed){changed=false;for(const f of forms){if(!f.deps.every(d=>values[d]!==undefined))continue;let x=parse(f.expr,values).value;if(!valid(f.target,x,group)){let key=f.label+f.target;if(!seen.has(key)){seen.add(key);issues.push('No physically valid result for '+f.target+' using '+f.label);}continue;}if(values[f.target]===undefined){values[f.target]=x;trails[f.target]={...f,result:x};changed=true;}}}for(const f of forms){if(values[f.target]===undefined||!f.deps.every(d=>values[d]!==undefined))continue;let x=parse(f.expr,values).value;if(Number.isFinite(x)&&Math.abs(x-values[f.target])>1e-6+1e-3*Math.max(Math.abs(x),Math.abs(values[f.target]))&&!seen.has(f.label)){seen.add(f.label);issues.push('Conflicting values: '+f.label);}}let suggestions=forms.filter(f=>values[f.target]===undefined).map(f=>({target:f.target,missing:f.deps.filter(d=>values[d]===undefined)})).filter(f=>f.missing.length);suggestions.sort((a,b)=>a.missing.length-b.missing.length);return {values,trails,issues,suggestions};}
// Share only quantities that represent the same physical system, not matching symbols.
const maps={decay:id=>'nuclear_'+id,gas:id=>'gas_'+id,solutions:id=>'solution_'+id,osmotic:id=>['i','osm','T'].includes(id)?'solution_'+id:'solution_'+id,colligative:id=>'solution_'+id,kinetics:id=>'reaction_'+({k:'k1'}[id]||id),arrhenius:id=>'reaction_'+id};
units.density={'g/mL':1000,'g/L':1,'kg/L':1000,'kg/m³':1};
const all={title:'All connected equations',vars:[],eqs:[]},known=new Set();
for(const [key,g] of Object.entries(groups)){if(key==='custom')continue;const map=maps[key];for(const variable of g.vars){const id=map(variable.id);if(!known.has(id)){known.add(id);all.vars.push({...variable,id,label:({nuclear:'Nuclear',gas:'Gas',solution:'Solution',reaction:'Reaction'})[id.split('_')[0]]+' · '+variable.label,context:g.title});}}for(const e of g.eqs){let forms={};for(const [target,expr] of Object.entries(e.forms)){forms[map(target)]=expr.replace(/\b[A-Za-z_]\w*\b/g,t=>g.vars.some(v=>v.id===t)?map(t):t);}all.eqs.push({label:g.title+': '+e.label,forms});}}
groups.all=all;
const api={groups,units,parse,convert,solve,valid};if(typeof module!=='undefined')module.exports=api;root.ChemEngine=api;
})(typeof globalThis!=='undefined'?globalThis:this);

