/* Explicit, reversible relationships. Each prefix represents one problem/system. */
(function(root){
'use strict';const E=root.ChemEngine,g=E.groups.all;
Object.assign(E.units,{money:{'currency units':1},fractionRate:{'%':.01,'decimal':1},years:{yr:1,month:1/12},periods:{periods:1},entropy:{'J/(mol·K)':1,'kJ/(mol·K)':1000},specificHeat:{'J/(kg·K)':1},heatCapacity:{'J/K':1},deltaTemp:{K:1,'°C':1},area:{'m²':1,'cm²':.0001},fluidVolume:{'m³':1,L:.001,mL:.000001},momentum:{'kg·m/s':1},spring:{'N/m':1},capacitance:{F:1,'µF':1e-6,'nF':1e-9},fieldStrength:{'N/C':1},surfaceDensity:{'individuals/m²':1},massConcentration:{'g/L':1,'mg/L':.001},productivity:{'J/(m²·yr)':1},ratio:{fraction:1,'%':.01}});
function net(prefix,title,vars,relations,note=''){const ids=new Set(vars.map(v=>v[0]));const map=id=>prefix+'_'+id;for(const [id,label,type='plain',domain] of vars){if(!g.vars.some(v=>v.id===map(id)))g.vars.push({id:map(id),label:title+' · '+label,type,context:title,hint:'',domain});}for(const [label,forms,guard] of relations){const mapped={};for(const [id,expr] of Object.entries(forms))mapped[map(id)]=expr.replace(/\b[A-Za-z_]\w*\b/g,t=>ids.has(t)?map(t):t);g.eqs.push({label:title+': '+label+(note?' ('+note+')':''),forms:mapped,...(guard?{guard:{...guard,id:map(guard.id)}}:{})});}}
E.addNetwork=net;const money=(id,label,domain)=>[id,label,'money',domain],rate=(id,label,domain='rate')=>[id,label,'fractionRate',domain];
net('interest','Simple interest',[money('P','Principal'),money('I','Interest','signed'),money('A','Final balance'),rate('r','Annual interest rate'),['t','Time','years']], [['I = Prt',{I:'P*r*t',P:'I/(r*t)',r:'I/(P*t)',t:'I/(P*r)'}],['A = P + I',{A:'P+I',P:'A-I',I:'A-P'}]],'fixed rate; rates can be entered as percent; one currency throughout');
net('compound','Compound growth',[money('P','Starting balance'),money('A','Final balance'),money('gain','Growth amount','signed'),rate('r','Nominal annual rate'),['m','Compounds per year','plain','positiveInteger'],['t','Time','years'],rate('effective','Effective annual rate')],[['A = P(1+r/m)^(mt)',{A:'P*(1+r/m)^(m*t)',P:'A/(1+r/m)^(m*t)',r:'m*((A/P)^(1/(m*t))-1)',t:'ln(A/P)/(m*ln(1+r/m))'}],['Effective annual rate',{effective:'(1+r/m)^m-1',r:'m*((1+effective)^(1/m)-1)'}],['Growth amount',{gain:'A-P',A:'P+gain',P:'A-gain'}]],'constant nominal rate and compounding; no deposits, fees or taxes');
net('continuous','Continuous growth',[money('P','Starting balance'),money('A','Final balance'),rate('r','Annual continuous rate'),['t','Time','years']],[['A = P exp(rt)',{A:'P*exp(r*t)',P:'A*exp(-r*t)',r:'ln(A/P)/t',t:'ln(A/P)/r'}]],'continuous compounding; constant rate');
net('loan','Fixed-payment loan',[money('P','Amount borrowed'),money('payment','Payment per period'),rate('r','Interest rate per payment period','nonnegative'),['n','Number of payments','periods','positive'],money('total','Total payments'),money('interest','Total interest')],[['Payment = Pr/[1−(1+r)^−n]',{payment:'P*r/(1-(1+r)^(-n))',P:'payment*(1-(1+r)^(-n))/r',n:'-ln(1-P*r/payment)/ln(1+r)'},{id:'r',not:0}],['Zero-interest payments',{payment:'P/n',P:'payment*n',n:'P/payment'},{id:'r',equals:0}],['Total payments',{total:'payment*n',payment:'total/n',n:'total/payment'}],['Total interest',{interest:'total-P',total:'P+interest',P:'total-interest'}]],'equal end-of-period payments; fixed nonnegative rate; excludes fees; n may be fractional mathematically');
net('annuity','Regular savings',[money('deposit','Deposit per period'),money('FV','Future value of deposits'),money('PV','Present value of deposits'),rate('r','Rate per deposit period'),['n','Number of deposits','periods','positive']],[['Ordinary annuity future value',{FV:'deposit*((1+r)^n-1)/r',deposit:'FV*r/((1+r)^n-1)',n:'ln(1+FV*r/deposit)/ln(1+r)'},{id:'r',not:0}],['Ordinary annuity present value',{PV:'deposit*(1-(1+r)^(-n))/r',deposit:'PV*r/(1-(1+r)^(-n))'},{id:'r',not:0}],['Zero-rate annuity',{FV:'deposit*n',PV:'deposit*n',deposit:'FV/n',n:'FV/deposit'},{id:'r',equals:0}]],'equal deposits at period end; no starting balance; constant rate');
net('discount','Discounted cash flow',[money('PV','Present value'),money('FV','Future cash flow'),rate('r','Discount rate per period'),['n','Periods until cash flow','periods'],money('cost','Initial cost'),money('NPV','Net present value','signed')],[['PV = FV/(1+r)^n',{PV:'FV/(1+r)^n',FV:'PV*(1+r)^n',r:'(FV/PV)^(1/n)-1',n:'ln(FV/PV)/ln(1+r)'}],['NPV = PV − initial cost',{NPV:'PV-cost',PV:'NPV+cost',cost:'PV-NPV'}]],'single future cash flow; rates greater than −100%; does not sum arbitrary cash-flow schedules');
net('return','Investment return',[money('initial','Initial investment'),money('final','Final investment value'),money('income','Income received'),rate('ROI','Total return','signed'),rate('CAGR','Annualized growth rate'),['t','Holding time','years'],rate('nominal','Nominal annual return'),rate('inflation','Annual inflation'),rate('real','Real annual return')],[['Total return including income',{ROI:'(final-initial+income)/initial',final:'initial*(1+ROI)-income',initial:'(final+income)/(1+ROI)',income:'ROI*initial-final+initial'}],['CAGR excludes distributions',{CAGR:'(final/initial)^(1/t)-1',final:'initial*(1+CAGR)^t',initial:'final/(1+CAGR)^t',t:'ln(final/initial)/ln(1+CAGR)'}],['Real return (Fisher relationship)',{real:'(1+nominal)/(1+inflation)-1',nominal:'(1+real)*(1+inflation)-1',inflation:'(1+nominal)/(1+real)-1'}]],'constant annualization; reinvested distributions must be included in final value for CAGR');
net('business','Business & pricing',[money('revenue','Revenue'),money('cost','Total cost'),money('profit','Profit','signed'),rate('margin','Profit margin','signed'),rate('markup','Cost markup','signed'),money('price','Unit selling price'),money('variable','Unit variable cost'),money('fixed','Fixed costs'),['quantity','Units sold','plain'],['breakeven','Break-even units','plain']],[['Profit = revenue − cost',{profit:'revenue-cost',revenue:'profit+cost',cost:'revenue-profit'}],['Margin = profit/revenue',{margin:'profit/revenue',profit:'margin*revenue',revenue:'profit/margin'}],['Markup = profit/cost',{markup:'profit/cost',profit:'markup*cost',cost:'profit/markup'}],['Revenue = price × quantity',{revenue:'price*quantity',price:'revenue/quantity',quantity:'revenue/price'}],['Total cost = fixed + variable × quantity',{cost:'fixed+variable*quantity',fixed:'cost-variable*quantity',variable:'(cost-fixed)/quantity',quantity:'(cost-fixed)/variable'}],['Break-even units',{breakeven:'fixed/(price-variable)',fixed:'breakeven*(price-variable)',price:'fixed/breakeven+variable'}]],'linear single-product costs; mathematical break-even quantity is not rounded up');
net('purchase','Tax & discounts',[money('list','List price'),rate('discount','Discount rate','fraction'),money('net','Price after discount'),rate('tax','Sales tax rate','nonnegative'),money('total','Price including tax')],[['Discounted price',{net:'list*(1-discount)',list:'net/(1-discount)',discount:'1-net/list'}],['Tax-inclusive price',{total:'net*(1+tax)',net:'total/(1+tax)',tax:'total/net-1'}]],'user-supplied rates; tax applied after discount; no jurisdiction-specific tax rules');
net('budget','Budget & financial ratios',[money('income','Monthly income'),money('expenses','Monthly expenses'),money('surplus','Monthly surplus','signed'),money('debt','Monthly debt payments'),rate('DTI','Debt-to-income ratio','nonnegative'),money('fund','Emergency fund'),['months','Months covered','plain'],money('assets','Assets'),money('liabilities','Liabilities'),money('worth','Net worth','signed')],[['Surplus',{surplus:'income-expenses',income:'surplus+expenses',expenses:'income-surplus'}],['Debt-to-income ratio',{DTI:'debt/income',debt:'DTI*income',income:'debt/DTI'}],['Emergency-fund coverage',{months:'fund/expenses',fund:'months*expenses',expenses:'fund/months'}],['Net worth',{worth:'assets-liabilities',assets:'worth+liabilities',liabilities:'assets-worth'}]],'use the same currency and monthly basis; ratios are calculations, not lending criteria');
net('bond','Bond valuation',[money('face','Face value'),money('coupon','Coupon per period'),rate('yield','Yield per coupon period'),['n','Remaining coupon periods','periods','positive'],money('price','Bond price'),rate('current','Current yield per period')],[['Discounted coupons and redemption',{price:'coupon*(1-(1+yield)^(-n))/yield+face/(1+yield)^n',coupon:'(price-face/(1+yield)^n)*yield/(1-(1+yield)^(-n))'},{id:'yield',not:0}],['Zero-yield price',{price:'coupon*n+face',coupon:'(price-face)/n'},{id:'yield',equals:0}],['Current yield',{current:'coupon/price',coupon:'current*price',price:'coupon/current'}]],'fixed coupons paid at period end; excludes accrued interest and default risk; yield inversion is not supplied');
net('depreciation','Straight-line depreciation',[money('cost','Asset cost'),money('salvage','Salvage value'),['life','Useful life','years','positive'],money('annual','Annual depreciation'),['elapsed','Elapsed life','years'],money('book','Book value')],[['Annual depreciation',{annual:'(cost-salvage)/life',cost:'annual*life+salvage',salvage:'cost-annual*life',life:'(cost-salvage)/annual'}],['Book value during useful life',{book:'cost-annual*elapsed',elapsed:'(cost-book)/annual',cost:'book+annual*elapsed'}]],'straight line; elapsed time must not exceed useful life; no automatic tax depreciation rules');

net('acid','Acids & bases',[['H','Hydrogen-ion concentration','concentration','positive'],['OH','Hydroxide concentration','concentration','positive'],['pH','pH','plain','signed'],['pOH','pOH','plain','signed'],['Kw','Water ion product','plain','positive'],['pKw','pKw','plain','signed']],[['pH = −log[H+]',{pH:'-log(H)',H:'10^(-pH)'}],['pOH = −log[OH−]',{pOH:'-log(OH)',OH:'10^(-pOH)'}],['Kw = [H+][OH−]',{Kw:'H*OH',H:'Kw/OH',OH:'Kw/H'}],['pKw = −log Kw',{pKw:'-log(Kw)',Kw:'10^(-pKw)'}],['pH + pOH = pKw',{pH:'pKw-pOH',pOH:'pKw-pH',pKw:'pH+pOH'}]],'ideal dilute activities; enter Kw at the applicable temperature; no default pKw');
net('buffer','Buffer',[['pH','pH','plain','signed'],['pKa','pKa','plain','signed'],['Ka','Acid dissociation constant','plain','positive'],['base','Conjugate-base concentration','concentration','positive'],['acid','Weak-acid concentration','concentration','positive']],[['Henderson–Hasselbalch',{pH:'pKa+log(base/acid)',pKa:'pH-log(base/acid)',base:'acid*10^(pH-pKa)',acid:'base/10^(pH-pKa)'}],['pKa = −log Ka',{pKa:'-log(Ka)',Ka:'10^(-pKa)'}]],'buffer approximation; activity effects neglected');
net('weakacid','Monoprotic weak acid',[['C','Initial acid concentration','concentration','positive'],['x','Dissociated concentration','concentration'],['Ka','Dissociation constant','plain','positive'],['fraction','Dissociation fraction','ratio','fraction']],[['Exact quadratic, negligible water autoionization',{x:'2*Ka*C/(Ka+sqrt(Ka^2+4*Ka*C))',Ka:'x^2/(C-x)',C:'x+x^2/Ka'}],['Dissociation fraction',{fraction:'x/C',x:'fraction*C',C:'x/fraction'}]],'single weak acid with no initial conjugate base; no water-autoionization term');
net('thermochem','Reaction thermodynamics',[['H','Standard enthalpy change','energy','signed'],['S','Standard entropy change','entropy','signed'],['T','Temperature','temp','positive'],['G','Standard Gibbs energy change','energy','signed'],['K','Equilibrium constant','plain','positive'],['Q','Reaction quotient','plain','positive'],['actualG','Gibbs energy at given quotient','energy','signed']],[['ΔG° = ΔH° − TΔS°',{G:'H-T*S',H:'G+T*S',S:'(H-G)/T',T:'(H-G)/S'}],['ΔG° = −RT ln K',{G:'-8.314462618*T*ln(K)',K:'exp(-G/(8.314462618*T))',T:'-G/(8.314462618*ln(K))'}],['ΔG = ΔG° + RT ln Q',{actualG:'G+8.314462618*T*ln(Q)',G:'actualG-8.314462618*T*ln(Q)',Q:'exp((actualG-G)/(8.314462618*T))'}]],'same reaction and temperature; dimensionless activities for K and Q');
net('electrochem','Electrochemistry',[['E0','Standard cell potential','voltage','signed'],['E','Cell potential','voltage','signed'],['n','Electrons transferred','plain','positiveInteger'],['G','Standard Gibbs energy change','energy','signed'],['T','Temperature','temp','positive'],['Q','Reaction quotient','plain','positive'],['K','Equilibrium constant','plain','positive']],[['ΔG° = −nFE°',{G:'-n*96485.33212*E0',E0:'-G/(n*96485.33212)',n:'-G/(96485.33212*E0)'}],['Nernst equation',{E:'E0-8.314462618*T/(n*96485.33212)*ln(Q)',E0:'E+8.314462618*T/(n*96485.33212)*ln(Q)',Q:'exp((E0-E)*n*96485.33212/(8.314462618*T))'}],['Standard potential and equilibrium',{K:'exp(n*96485.33212*E0/(8.314462618*T))',E0:'8.314462618*T*ln(K)/(n*96485.33212)'}]],'activities, same reaction; Faraday constant in C/mol');
net('yield','Reaction yield',[['actual','Actual product mass','mass'],['theoretical','Theoretical product mass','mass','positive'],['percent','Percent yield','percent']],[['Percent yield',{percent:'100*actual/theoretical',actual:'percent*theoretical/100',theoretical:'100*actual/percent'}]],'pure product; observed yields can exceed 100% and may signal impurities');
net('stoich','Stoichiometry',[['reactant','Reactant amount','amount'],['product','Product amount','amount'],['a','Reactant coefficient','plain','positiveInteger'],['b','Product coefficient','plain','positiveInteger'],['M','Product molar mass','molarMass','positive'],['mass','Theoretical product mass','mass']],[['Balanced-equation mole ratio',{product:'reactant*b/a',reactant:'product*a/b'}],['Product mass',{mass:'product*M',product:'mass/M',M:'mass/product'}]],'user supplies balanced coefficients and limiting reactant; complete reaction');
net('zeroorder','Zero-order kinetics',[['initial','Initial concentration','concentration'],['remaining','Final concentration','concentration'],['k','Rate constant','enzymeRate','positive'],['t','Reaction time','time'],['half','Half-life','time']],[['[A] = [A]₀ − kt',{remaining:'initial-k*t',initial:'remaining+k*t',k:'(initial-remaining)/t',t:'(initial-remaining)/k'}],['Half-life',{half:'initial/(2*k)',initial:'2*k*half',k:'initial/(2*half)'}]],'constant zero-order rate until reactant depleted');
Object.assign(E.units,{secondRate:{'L/(mol·s)':1}});
net('secondorder','Second-order kinetics',[['initial','Initial concentration','concentration','positive'],['remaining','Final concentration','concentration','positive'],['k','Rate constant','secondRate','positive'],['t','Reaction time','time'],['half','Half-life','time']],[['1/[A] = 1/[A]₀ + kt',{remaining:'1/(1/initial+k*t)',initial:'1/(1/remaining-k*t)',k:'(1/remaining-1/initial)/t',t:'(1/remaining-1/initial)/k'}],['Half-life',{half:'1/(k*initial)',k:'1/(half*initial)',initial:'1/(k*half)'}]],'rate = k[A]²; constant temperature');

net('momentum','Momentum & impulse',[['m','Mass','physicalMass'],['v','Velocity','speed','signed'],['p','Momentum','momentum','signed'],['F','Average force','force','signed'],['t','Impulse duration','time'],['J','Impulse','momentum','signed'],['u','Initial velocity','speed','signed']],[['p = mv',{p:'m*v',m:'p/v',v:'p/m'}],['Impulse = FΔt',{J:'F*t',F:'J/t',t:'J/F'}],['Impulse = m(v−u)',{J:'m*(v-u)',v:'u+J/m',u:'v-J/m',m:'J/(v-u)'}]],'signed one-dimensional system; constant mass');
net('spring','Spring',[['k','Spring constant','spring','positive'],['x','Stretch magnitude','length'],['F','Force magnitude','force'],['energy','Elastic potential energy','work'],['m','Oscillating mass','physicalMass','positive'],['period','Oscillation period','time']],[['Hooke force magnitude',{F:'k*x',k:'F/x',x:'F/k'}],['Elastic energy',{energy:'k*x^2/2',k:'2*energy/x^2',x:'sqrt(2*energy/k)'}],['Period = 2π sqrt(m/k)',{period:'2*pi*sqrt(m/k)',m:'k*(period/(2*pi))^2',k:'4*pi^2*m/period^2'}]],'ideal spring within elastic limit; undamped oscillation');
net('circular','Circular motion',[['m','Mass','physicalMass'],['v','Speed','speed'],['r','Radius','length','positive'],['a','Centripetal acceleration','acceleration'],['F','Centripetal force','force'],['period','Period','time','positive']],[['a = v²/r',{a:'v^2/r',v:'sqrt(a*r)',r:'v^2/a'}],['F = ma',{F:'m*a',m:'F/a',a:'F/m'}],['v = 2πr/T',{v:'2*pi*r/period',r:'v*period/(2*pi)',period:'2*pi*r/v'}]],'uniform circular motion');
net('gravity','Universal gravitation',[['m1','First mass','physicalMass'],['m2','Second mass','physicalMass'],['r','Center-to-center distance','length','positive'],['F','Gravitational force','force'],['U','Gravitational potential energy','work','signed']],[['F = Gm₁m₂/r²',{F:'6.67430e-11*m1*m2/r^2',m1:'F*r^2/(6.67430e-11*m2)',m2:'F*r^2/(6.67430e-11*m1)',r:'sqrt(6.67430e-11*m1*m2/F)'}],['U = −Gm₁m₂/r',{U:'-6.67430e-11*m1*m2/r',r:'-6.67430e-11*m1*m2/U'}]],'point masses or spherically symmetric bodies; U zero at infinity');
net('fluid','Fluid pressure & buoyancy',[['rho','Fluid density','density'],['h','Depth','length'],['g','Gravitational acceleration','acceleration'],['P','Gauge pressure','pressure'],['area','Surface area','area'],['F','Pressure force','force'],['volume','Displaced volume','fluidVolume'],['buoyancy','Buoyant force','force']],[['Gauge pressure = ρgh',{P:'rho*g*h/101325',rho:'P*101325/(g*h)',h:'P*101325/(rho*g)',g:'P*101325/(rho*h)'}],['Pressure force',{F:'P*101325*area',P:'F/(101325*area)',area:'F/(P*101325)'}],['Buoyant force',{buoyancy:'rho*g*volume',volume:'buoyancy/(rho*g)',rho:'buoyancy/(g*volume)'}]],'static incompressible fluid; density base kg/m³; gauge pressure excludes atmosphere');
net('heat','Calorimetry',[['m','Mass','physicalMass'],['c','Specific heat','specificHeat','positive'],['delta','Temperature change','deltaTemp','signed'],['Q','Heat transferred','work','signed'],['capacity','Heat capacity','heatCapacity']],[['Q = mcΔT',{Q:'m*c*delta',m:'Q/(c*delta)',c:'Q/(m*delta)',delta:'Q/(m*c)'}],['Heat capacity = mc',{capacity:'m*c',m:'capacity/c',c:'capacity/m'}]],'constant specific heat; no phase change; signed heat and temperature change');
net('capacitor','Capacitor',[['C','Capacitance','capacitance','positive'],['V','Voltage magnitude','voltage'],['Q','Charge magnitude','charge'],['energy','Stored energy','work']],[['Q = CV',{Q:'C*V',C:'Q/V',V:'Q/C'}],['Energy = CV²/2',{energy:'C*V^2/2',C:'2*energy/V^2',V:'sqrt(2*energy/C)'}]],'ideal capacitor');
net('photon','Photon',[['f','Frequency','frequency','positive'],['lambda','Vacuum wavelength','length','positive'],['E','Photon energy','work']],[['c = fλ',{f:'299792458/lambda',lambda:'299792458/f'}],['E = hf',{E:'6.62607015e-34*f',f:'E/6.62607015e-34'}]],'vacuum; exact SI Planck constant and light speed');
net('lens','Thin lens',[['object','Object distance','length','signed'],['image','Image distance','length','signed'],['f','Focal length','length','signed'],['magnification','Signed magnification','plain','signed'],['objectHeight','Object height','length','signed'],['imageHeight','Image height','length','signed']],[['1/f = 1/do + 1/di',{f:'1/(1/object+1/image)',object:'1/(1/f-1/image)',image:'1/(1/f-1/object)'}],['Magnification = −di/do',{magnification:'-image/object',image:'-magnification*object',object:'-image/magnification'}],['Height ratio',{magnification:'imageHeight/objectHeight',imageHeight:'magnification*objectHeight',objectHeight:'imageHeight/magnification'}]],'paraxial thin lens; real-is-positive distance convention; infinite images remain unresolved');

net('ecology','Population sampling',[['count','Individuals counted','count'],['area','Sample area','area','positive'],['density','Population density','surfaceDensity'],['marked','Initially marked','count'],['sample','Recapture sample size','count'],['recaptured','Marked recaptures','count','positive'],['estimate','Estimated population','count']],[['Density = count/area',{density:'count/area',count:'density*area',area:'count/density'}],['Lincoln–Petersen estimator',{estimate:'marked*sample/recaptured',marked:'estimate*recaptured/sample',sample:'estimate*recaptured/marked',recaptured:'marked*sample/estimate'}]],'closed population; random mixing; equal capture probability; estimator not rounded');
net('productivity','Ecosystem productivity',[['gross','Gross primary productivity','productivity'],['respiration','Respiration','productivity'],['net','Net primary productivity','productivity'],['consumer','Consumer production','productivity'],['efficiency','Trophic transfer efficiency','ratio','fraction']],[['NPP = GPP − respiration',{net:'gross-respiration',gross:'net+respiration',respiration:'gross-net'}],['Transfer efficiency',{efficiency:'consumer/net',consumer:'efficiency*net',net:'consumer/efficiency'}]],'same area and time interval; energy-based production');
net('enzyme','Enzyme kinetics',[['v','Reaction rate','enzymeRate'],['vmax','Maximum rate','enzymeRate'],['S','Substrate concentration','concentration'],['Km','Michaelis constant','concentration'],['kcat','Turnover number','rate'],['enzyme','Total enzyme concentration','concentration']],[['Vmax = kcat[E]total',{vmax:'kcat*enzyme',kcat:'vmax/enzyme',enzyme:'vmax/kcat'}]],'same enzyme system; catalytic-site concentration');
net('inhibition','Competitive enzyme inhibition',[['v','Reaction rate','enzymeRate'],['vmax','Maximum rate','enzymeRate'],['S','Substrate concentration','concentration'],['Km','Michaelis constant','concentration'],['I','Inhibitor concentration','concentration'],['Ki','Inhibition constant','concentration','positive'],['alpha','Inhibition factor','plain','positive']],[['α = 1 + [I]/Ki',{alpha:'1+I/Ki',I:'(alpha-1)*Ki',Ki:'I/(alpha-1)'}],['v = Vmax S/(αKm+S)',{v:'vmax*S/(alpha*Km+S)',vmax:'v*(alpha*Km+S)/S',S:'v*alpha*Km/(vmax-v)',Km:'S*(vmax/v-1)/alpha'}]],'pure competitive inhibition, steady state');
net('growthbalance','Population balance',[['initial','Initial population','count'],['final','Final population','count'],['births','Births','count'],['deaths','Deaths','count'],['immigration','Immigration','count'],['emigration','Emigration','count'],['change','Net population change','count','signed']],[['Net change',{change:'births-deaths+immigration-emigration',births:'change+deaths-immigration+emigration',deaths:'births+immigration-emigration-change'}],['Final population',{final:'initial+change',initial:'final-change',change:'final-initial'}]],'counts over the same interval');
net('qten','Biological temperature response',[['rate1','Rate at temperature 1','enzymeRate','positive'],['rate2','Rate at temperature 2','enzymeRate','positive'],['T1','Temperature 1','temp'],['T2','Temperature 2','temp'],['Q10','Q10 factor','plain','positive']],[['Q10 rate relationship',{rate2:'rate1*Q10^((T2-T1)/10)',rate1:'rate2/Q10^((T2-T1)/10)',Q10:'(rate2/rate1)^(10/(T2-T1))'}]],'empirical constant Q10 over the given temperature interval');
net('loan','Fixed-payment loan',[['APR','Nominal annual interest rate','fractionRate','nonnegative'],['frequency','Payments per year','plain','positiveInteger'],['years','Loan term','years','positive'],['r','Interest rate per payment period','fractionRate','nonnegative'],['n','Number of payments','periods','positive'],['P','Amount borrowed','money'],['payment','Payment per period','money'],['paid','Payments already made','periods'],['balance','Remaining principal','money']],[['Annual rate to periodic rate',{r:'APR/frequency',APR:'r*frequency',frequency:'APR/r'}],['Loan term to payment count',{n:'years*frequency',years:'n/frequency',frequency:'n/years'}],['Outstanding principal after payments',{balance:'P*(1+r)^paid-payment*((1+r)^paid-1)/r'},{id:'r',not:0}],['Zero-rate outstanding principal',{balance:'P-payment*paid'},{id:'r',equals:0}]],'fixed rate; balance is immediately after a payment; enter paid count within loan term');
net('perpetuity','Perpetuity',[money('PV','Present value'),money('payment','Payment per period'),rate('r','Discount rate per period','positive')],[['PV = payment/r',{PV:'payment/r',payment:'PV*r',r:'payment/PV'}]],'constant payments forever; first payment one period from now');
net('growingperpetuity','Growing perpetuity',[money('PV','Present value'),money('payment','Next-period payment'),rate('r','Discount rate per period'),rate('growth','Payment growth per period')],[['PV = next payment/(r−g)',{PV:'payment/(r-growth)',payment:'PV*(r-growth)',r:'payment/PV+growth',growth:'r-payment/PV'}]],'constant growth forever; discount rate must exceed growth; first payment one period from now');
net('capm','CAPM',[rate('riskfree','Risk-free rate'),rate('market','Expected market return'),['beta','Beta','plain','signed'],rate('expected','Expected return')],[['Expected return = risk-free + beta × premium',{expected:'riskfree+beta*(market-riskfree)',riskfree:'(expected-beta*market)/(1-beta)',market:'riskfree+(expected-riskfree)/beta',beta:'(expected-riskfree)/(market-riskfree)'}]],'user-supplied expectations on the same time basis; model estimate');
net('wacc','Cost of capital',[money('equity','Market equity value'),money('debt','Market debt value'),rate('costEquity','Cost of equity'),rate('costDebt','Cost of debt'),rate('tax','Corporate tax rate','fraction'),rate('WACC','Weighted average cost of capital')],[['WACC = equity weight × Re + debt weight × Rd(1−tax)',{WACC:'equity/(equity+debt)*costEquity+debt/(equity+debt)*costDebt*(1-tax)',costEquity:'(WACC*(equity+debt)-debt*costDebt*(1-tax))/equity',costDebt:'(WACC*(equity+debt)-equity*costEquity)/(debt*(1-tax))'}]],'market weights; stated tax shield; same annual basis');
net('stock','Stock metrics',[money('price','Share price'),money('earnings','Earnings per share','signed'),['PE','Price-to-earnings ratio','plain','signed'],money('dividend','Annual dividend per share'),rate('yield','Dividend yield','nonnegative'),['shares','Shares outstanding','plain','positive'],money('marketcap','Market capitalization')],[['P/E',{PE:'price/earnings',price:'PE*earnings',earnings:'price/PE'}],['Dividend yield',{yield:'dividend/price',dividend:'yield*price',price:'dividend/yield'}],['Market capitalization',{marketcap:'price*shares',price:'marketcap/shares',shares:'marketcap/price'}]],'consistent share class and earnings period; negative P/E is a mathematical ratio');
net('liquidity','Liquidity ratios',[money('assets','Current assets'),money('inventory','Inventory'),money('liabilities','Current liabilities'),['current','Current ratio','plain'],['quick','Quick ratio','plain']],[['Current ratio',{current:'assets/liabilities',assets:'current*liabilities',liabilities:'assets/current'}],['Quick ratio',{quick:'(assets-inventory)/liabilities',inventory:'assets-quick*liabilities',assets:'quick*liabilities+inventory',liabilities:'(assets-inventory)/quick'}]],'simplified quick ratio; inventory must not exceed current assets');
net('gas','Gas',[['mass','Mass','mass'],['V','Volume','volume'],['density','Gas density','density'],['M','Molar mass','molarMass'],['P','Pressure','pressure'],['T','Temperature','temp']],[['Gas density = mass/volume',{density:'mass/V',mass:'density*V',V:'mass/density'}],['Ideal-gas density',{density:'P*M/(0.082057366*T)',P:'density*0.082057366*T/M',M:'density*0.082057366*T/P',T:'P*M/(density*0.082057366)'}]],'ideal gas; density canonical g/L');
net('raoult','Raoult law',[['x','Solvent mole fraction','ratio','fraction'],['P0','Pure-solvent vapor pressure','pressure'],['P','Solution vapor pressure','pressure'],['lowering','Vapor-pressure lowering','pressure']],[['P = x P°',{P:'x*P0',x:'P/P0',P0:'P/x'}],['Pressure lowering',{lowering:'P0-P',P:'P0-lowering',P0:'P+lowering'}]],'ideal solution with a nonvolatile solute');
net('solubility','1:1 salt solubility',[['s','Molar solubility','concentration'],['common','Initial common-ion concentration','concentration'],['Ksp','Solubility product','plain','positive']],[['Ksp = s(s + common)',{Ksp:'s*(s+common)',s:'2*Ksp/(common+sqrt(common^2+4*Ksp))',common:'Ksp/s-s'}]],'1:1 salt; one initially present common ion; enter zero explicitly when absent; ideal activities');
net('pcr','Ideal PCR amplification',[['initial','Initial DNA copies','plain'],['cycles','Cycles','plain','nonnegative'],['final','Final DNA copies','plain'],['efficiency','Per-cycle amplification efficiency','ratio','fraction']],[['Copies = initial × (1+efficiency)^cycles',{final:'initial*(1+efficiency)^cycles',initial:'final/(1+efficiency)^cycles',cycles:'ln(final/initial)/ln(1+efficiency)',efficiency:'(final/initial)^(1/cycles)-1'}]],'constant efficiency; 100% doubles per cycle; no plateau');
net('allelecounts','Observed allele frequencies',[['AA','AA individuals','count'],['Aa','Aa individuals','count'],['aa','aa individuals','count'],['N','Total individuals','count'],['p','A allele frequency','ratio','fraction'],['q','a allele frequency','ratio','fraction']],[['Sample total',{N:'AA+Aa+aa',AA:'N-Aa-aa',Aa:'N-AA-aa',aa:'N-AA-Aa'}],['Observed A frequency',{p:'(2*AA+Aa)/(2*N)'}],['Observed a frequency',{q:'(2*aa+Aa)/(2*N)'}],['Two allele frequencies',{p:'1-q',q:'1-p'}]],'diploid, two alleles; observed frequencies do not assume Hardy–Weinberg equilibrium');
})(typeof globalThis!=='undefined'?globalThis:this);
