/* Bounded numeric tools: no eval, code execution, network or external dependencies. */
(function(root){'use strict';const E=root.ChemEngine;
function list(raw){const tokens=raw.trim().split(/[\s,;]+/);if(!raw.trim())return [];if(tokens.length>10000)throw Error('Use at most 10,000 observations.');const a=tokens.map(Number);if(a.some(x=>!Number.isFinite(x)))throw Error('Enter numbers separated by commas, spaces or new lines.');return a;}
function sample(x,y=[]){if(!x.length)throw Error('Enter at least one observation.');const n=x.length,mean=x.reduce((a,b)=>a+b/n,0);const ss=x.reduce((s,v)=>s+(v-mean)**2,0),sorted=[...x].sort((a,b)=>a-b),values={sample_n:n,sample_sum:mean*n,sample_mean:mean,sample_ss:ss,sample_min:sorted[0],sample_max:sorted[n-1],sample_median:n%2?sorted[(n-1)/2]:(sorted[n/2-1]+sorted[n/2])/2};const freq=new Map();for(const v of x)freq.set(v,(freq.get(v)||0)+1);const max=Math.max(...freq.values()),modes=[...freq].filter(([v,c])=>c===max);if(modes.length===1)values.sample_mode=modes[0][0];if(n>1)values.sample_s=Math.sqrt(ss/(n-1));if(y.length){if(y.length!==n||n<2)throw Error('Paired data need equal lists with at least two observations.');const my=y.reduce((a,b)=>a+b/n,0),syy=y.reduce((s,v)=>s+(v-my)**2,0),sxy=x.reduce((s,v,i)=>s+(v-mean)*(y[i]-my),0);if(ss===0||syy===0)throw Error('Regression needs variation in both lists.');const b=sxy/ss;Object.assign(values,{regression_xbar:mean,regression_ybar:my,regression_sx:Math.sqrt(ss/(n-1)),regression_sy:Math.sqrt(syy/(n-1)),regression_r:Math.max(-1,Math.min(1,sxy/Math.sqrt(ss*syy))),regression_b:b,regression_a:my-b*mean});}return values;}
function chi(observed,expected){if(!observed.length||observed.length!==expected.length)throw Error('Observed and expected lists must have matching lengths.');if(observed.some(x=>x<0)||expected.some(x=>x<=0))throw Error('Observed counts must be nonnegative; expected counts must be positive.');return {chisquare_chi:observed.reduce((s,o,i)=>s+(o-expected[i])**2/expected[i],0),chisquare_categories:observed.length};}
function diversity(counts){if(!counts.length||counts.some(x=>x<0)||counts.reduce((a,b)=>a+b,0)===0)throw Error('Enter nonnegative species counts with a positive total.');const total=counts.reduce((a,b)=>a+b,0);return {diversity_total:total,diversity_species:counts.filter(x=>x>0).length,diversity_index:1-counts.reduce((s,n)=>s+(n/total)**2,0)};}
function distribution(x,p){if(!x.length||x.length!==p.length||p.some(v=>v<0||v>1)||Math.abs(p.reduce((a,b)=>a+b,0)-1)>1e-8)throw Error('Values need matching probabilities between 0 and 1 that sum to 1.');const mean=x.reduce((s,v,i)=>s+v*p[i],0);return {distribution_mean:mean,distribution_sd:Math.sqrt(x.reduce((s,v,i)=>s+(v-mean)**2*p[i],0))};}
function f(expr,x){const r=E.parse(expr,{x});if(r.deps.some(d=>d!=='x')||!Number.isFinite(r.value))throw Error('Use a finite real function of x. Supported: arithmetic, powers, sin/cos/tan, asin/acos/atan, ln/log, exp, sqrt, abs and pi.');return r.value;}
function at(expr,x){const h=1e-4*Math.max(1,Math.abs(x)),y=f(expr,x),left=(y-f(expr,x-h))/h,right=(f(expr,x+h)-y)/h;if(Math.abs(left-right)>.02*Math.max(1,Math.abs(left),Math.abs(right)))throw Error('Derivative may be discontinuous or unstable at this point.');const d1=(f(expr,x+h)-f(expr,x-h))/(2*h),d2=(f(expr,x+h/2)-f(expr,x-h/2))/h;return {function_x:x,function_value:y,function_derivative:(4*d2-d1)/3,function_second:(f(expr,x+h)-2*y+f(expr,x-h))/h**2};}
function integral(expr,a,b){if(a===b)return {function_a:a,function_b:b,function_integral:0};function simpson(n){let sum=f(expr,a)+f(expr,b),step=(b-a)/n;for(let i=1;i<n;i++)sum+=(i%2?4:2)*f(expr,a+i*step);return sum*step/3;}let previous=simpson(128);for(let n=256;n<=8192;n*=2){const value=simpson(n);if(Math.abs(value-previous)<1e-8*Math.max(1,Math.abs(value)))return {function_a:a,function_b:b,function_integral:value};previous=value;}throw Error('Integral did not converge. Split the interval or check for singularities; improper integrals are not supported.');}
function normalcdf(z){if(z===0)return .5;const x=Math.abs(z),t=1/(1+.2316419*x),tail=Math.exp(-x*x/2)/Math.sqrt(2*Math.PI)*t*(.319381530+t*(-.356563782+t*(1.781477937+t*(-1.821255978+t*1.330274429))));return z>0?1-tail:tail;}
function inverseNormal(p){if(!(p>0&&p<1))return NaN;let a=-12,b=12;for(let i=0;i<100;i++){const m=(a+b)/2;if(normalcdf(m)<p)a=m;else b=m;}return (a+b)/2;}
E.functions.normalcdf=normalcdf;E.functions.invnormal=inverseNormal;
E.functions.logfactorial=n=>{if(!Number.isInteger(n)||n<0||n>10000)return NaN;let s=0;for(let i=2;i<=n;i++)s+=Math.log(i);return s;};E.functions.iszero=x=>x===0?1:0;
root.CalcTools={list,sample,chi,diversity,distribution,at,integral,f,normalcdf,inverseNormal};if(typeof module!=='undefined')module.exports=root.CalcTools;
})(typeof globalThis!=='undefined'?globalThis:this);
