(function(root){
'use strict';
const order=x=>x===0?0:Math.floor(Math.log10(Math.abs(x))+1e-12);
const sf=(x,p)=>p===-Infinity?Infinity:Math.max(1,order(x)-p+1);
function read(raw){let [mantissa,exponent='0']=raw.trim().toLowerCase().replace(/^[+-]/,'').split('e'),e=Number(exponent),dot=mantissa.includes('.');let digits=mantissa.replace('.','').replace(/^0+/,'');let count=dot?digits.length:digits.replace(/0+$/,'').length;if(!count)count=dot?Math.max(1,mantissa.split('.')[1].length):1;let p=dot?e-mantissa.split('.')[1].length:e+(mantissa.match(/0+$/)?.[0].length||0);return {sf:count,p};}
function base(raw,unit,type,id){let x=Number(raw),m=read(raw),factor=ChemEngine.units[type][unit];if(type==='temp'&&unit==='°C'&&!/(^|_)(df|db)$/.test(id)){let value=x+273.15;return {value,p:m.p};}let value=x*factor;return {value,p:x===0?m.p+Math.log10(factor):order(value)-m.sf+1};}
function evaluate(expr,values,precision){let ts=expr.match(/(?:\d*\.\d+|\d+\.?\d*)(?:[eE][+-]?\d+)?|[A-Za-z_]\w*|[()+\-*/^]/g),i=0;const exact=value=>({value,p:-Infinity});function atom(){let t=ts[i++];if(t==='+'||t==='-'){let a=atom();return {...a,value:t==='-'?-a.value:a.value};}if(t==='('){let a=sum();i++;return a;}if(/^[\d.]/.test(t))return exact(Number(t));if(ts[i]==='('){i++;let a=sum();i++;let value=({ln:Math.log,log:Math.log10,exp:Math.exp,sqrt:Math.sqrt,abs:Math.abs})[t](a.value);if(a.p===-Infinity)return exact(value);if(t==='ln'||t==='log')return {value,p:-sf(a.value,a.p)};if(t==='exp')return {value,p:order(value)-Math.max(1,-a.p)+1};return {value,p:t==='abs'?a.p:order(value)-sf(a.value,a.p)+1};}if(t==='pi')return exact(Math.PI);return {value:values[t],p:precision[t]?.p??-Infinity};}
function combine(a,b,op){let value=op==='+'?a.value+b.value:op==='-'?a.value-b.value:op==='*'?a.value*b.value:op==='/'?a.value/b.value:Math.pow(a.value,b.value);let p;if(op==='+'||op==='-')p=Math.max(a.p,b.p);else{let n=Math.min(sf(a.value,a.p),sf(b.value,b.p));p=n===Infinity?-Infinity:order(value)-n+1;}return {value,p};}
function power(){let a=atom();if(ts[i]==='^'){i++;a=combine(a,power(),'^');}return a;}function product(){let a=power();while(['*','/'].includes(ts[i])){let op=ts[i++];a=combine(a,power(),op);}return a;}function sum(){let a=product();while(['+','-'].includes(ts[i])){let op=ts[i++];a=combine(a,product(),op);}return a;}return sum();}
function propagate(result,inputs){let precision={...inputs};for(const [id,t] of Object.entries(result.trails))precision[id]=evaluate(t.expr,result.values,precision);return precision;}
function format(x,meta,unit,type,id){if(!meta||meta.p===-Infinity)return Number(x.toPrecision(7)).toString();let p=meta.p,factor=ChemEngine.units[type][unit];if(!(type==='temp'&&unit==='°C'&&!/(^|_)(df|db)$/.test(id))){p=x===0?p-Math.log10(factor):order(x)-sf(meta.value,p)+1;}p=Math.round(p);let n=Math.max(1,Math.min(100,order(x)-p+1));if(p>0||Math.abs(x)>=1e7||(x!==0&&Math.abs(x)<1e-4))return x.toExponential(n-1);return x.toFixed(Math.max(0,Math.min(100,-p)));}
const api={read,base,evaluate,propagate,format};root.ChemPrecision=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
