/* Common introductory physics and biology models. Each prefix denotes one system. */
(function(root){
const E=root.ChemEngine,all=E.groups.all;
Object.assign(E.units,{length:{m:1,cm:.01,mm:.001,km:1000},speed:{'m/s':1,'km/h':1/3.6},acceleration:{'m/s²':1},physicalMass:{kg:1,g:.001},force:{N:1},work:{J:1,kJ:1000},power:{W:1,kW:1000},frequency:{Hz:1,kHz:1000},voltage:{V:1,mV:.001},current:{A:1,mA:.001},resistance:{Ω:1,'kΩ':1000},charge:{C:1},bioRate:{'s⁻¹':1,'h⁻¹':1/3600,'day⁻¹':1/86400},bioTime:{s:1,h:3600,day:86400},count:{'individuals':1},enzymeRate:{'mol/L/s':1,'mmol/L/s':.001}});
function network(prefix,title,vars,relations,note){const ids=new Set(vars.map(v=>v[0]));for(const [id,label,type='plain'] of vars)all.vars.push({id:prefix+'_'+id,label:title+' · '+label,type,context:title,hint:''});for(const [label,forms] of relations){let mapped={};for(const [id,expr] of Object.entries(forms))mapped[prefix+'_'+id]=expr.replace(/\b[A-Za-z_]\w*\b/g,t=>ids.has(t)?prefix+'_'+t:t);all.eqs.push({label:title+': '+label+(note?' ('+note+')':''),forms:mapped});}}
network('motion','Motion', [['d','Displacement','length'],['v','Average velocity','speed'],['t','Elapsed time','time'],['u','Initial velocity','speed'],['vf','Final velocity','speed'],['a','Acceleration','acceleration']], [
['d = v̄t',{d:'v*t',v:'d/t',t:'d/v'}],['vf = u + at',{vf:'u+a*t',u:'vf-a*t',a:'(vf-u)/t',t:'(vf-u)/a'}],['d = (u + vf)t/2',{d:'(u+vf)*t/2',u:'2*d/t-vf',vf:'2*d/t-u',t:'2*d/(u+vf)'}]],'signed 1D motion; vf/u/a equations assume constant acceleration');
network('mechanics','Mechanics',[['m','Mass','physicalMass'],['a','Acceleration','acceleration'],['F','Net force','force'],['v','Speed','speed'],['KE','Kinetic energy','work'],['h','Height','length'],['g','Gravitational acceleration','acceleration'],['PE','Gravitational potential energy','work'],['W','Work','work'],['d','Distance along force','length'],['P','Power','power'],['t','Elapsed time','time']],[
['F = ma',{F:'m*a',m:'F/a',a:'F/m'}],['KE = mv²/2',{KE:'m*v^2/2',m:'2*KE/v^2',v:'sqrt(2*KE/m)'}],['PE = mgh',{PE:'m*g*h',m:'PE/(g*h)',g:'PE/(m*h)',h:'PE/(m*g)'}],['W = Fd',{W:'F*d',F:'W/d',d:'W/F'}],['P = W/t',{P:'W/t',W:'P*t',t:'W/P'}]],'magnitudes; work assumes constant force parallel to displacement');
network('wave','Waves',[['v','Wave speed','speed'],['f','Frequency','frequency'],['lambda','Wavelength','length'],['period','Period','time']],[['v = fλ',{v:'f*lambda',f:'v/lambda',lambda:'v/f'}],['Period = 1/f',{period:'1/f',f:'1/period'}]]);
network('circuit','DC circuit',[['V','Voltage','voltage'],['I','Current','current'],['R','Resistance','resistance'],['P','Power','power'],['Q','Charge','charge'],['t','Elapsed time','time'],['energy','Electrical energy','work']],[['V = IR',{V:'I*R',I:'V/R',R:'V/I'}],['P = VI',{P:'V*I',V:'P/I',I:'P/V'}],['Q = It',{Q:'I*t',I:'Q/t',t:'Q/I'}],['Energy = Pt',{energy:'P*t',P:'energy/t',t:'energy/P'}]],'steady DC, ohmic resistor');
network('population','Population',[['N0','Initial population','count'],['N','Final population','count'],['r','Growth rate','bioRate'],['t','Elapsed time','bioTime'],['doubling','Doubling time','bioTime']],[['N = N₀ exp(rt)',{N:'N0*exp(r*t)',N0:'N*exp(-r*t)',r:'ln(N/N0)/t',t:'ln(N/N0)/r'}],['Doubling time = ln(2)/r',{doubling:'ln(2)/r',r:'ln(2)/doubling'}]],'exponential growth; no resource limitation');
network('logistic','Logistic growth',[['N0','Initial population','count'],['N','Final population','count'],['r','Intrinsic growth rate','bioRate'],['t','Elapsed time','bioTime'],['K','Carrying capacity','count']],[['N = K/[1+(K/N₀−1)exp(−rt)]',{N:'K/(1+(K/N0-1)*exp(-r*t))',N0:'K/(1+(K/N-1)*exp(r*t))',r:'-ln((K/N-1)/(K/N0-1))/t',t:'-ln((K/N-1)/(K/N0-1))/r'}]],'positive populations, constant carrying capacity; inverse rate/time needs N and N₀ on the same side of K');
network('enzyme','Enzyme kinetics',[['v','Reaction rate','enzymeRate'],['vmax','Maximum rate','enzymeRate'],['S','Substrate concentration','concentration'],['Km','Michaelis constant','concentration']],[['v = Vmax S/(Km+S)',{v:'vmax*S/(Km+S)',vmax:'v*(Km+S)/S',S:'v*Km/(vmax-v)',Km:'S*(vmax/v-1)'}]],'Michaelis–Menten steady-state model, no inhibition');
network('genetics','Hardy–Weinberg',[['p','Allele A frequency'],['q','Allele a frequency'],['AA','AA genotype frequency'],['Aa','Aa genotype frequency'],['aa','aa genotype frequency']],[['p + q = 1',{p:'1-q',q:'1-p'}],['AA = p²',{AA:'p^2',p:'sqrt(AA)'}],['aa = q²',{aa:'q^2',q:'sqrt(aa)'}],['Aa = 2pq',{Aa:'2*p*q',p:'Aa/(2*q)',q:'Aa/(2*p)'}]],'two alleles, Hardy–Weinberg equilibrium; frequencies are fractions');
network('absorbance','Spectrophotometry',[['A','Absorbance'],['epsilon','Molar absorptivity','plain'],['l','Path length','length'],['c','Concentration','concentration'],['transmission','Transmittance fraction']],[['A = εlc',{A:'epsilon*l*c',epsilon:'A/(l*c)',l:'A/(epsilon*c)',c:'A/(epsilon*l)'}],['A = −log₁₀(T)',{A:'-log(transmission)',transmission:'10^(-A)'}]],'Beer–Lambert; absorptivity in L·mol⁻¹·m⁻¹, path length in meters');
})(typeof globalThis!=='undefined'?globalThis:this);

