// App integration helpers; loaded after the main app's functions are declared.
function setupGoals(){const s=current();$("inputQuantities").innerHTML=group().vars.map(v=>`<option value="${esc(v.label)}"></option>`).join("");renderTargetOptions();$('chemicalPanel').hidden=topic!=='all';$('solventPanel').hidden=topic!=='all';$('soluteFormula').value=s.chemical?.solute||'';$('gasFormula').value=s.chemical?.gas||'';$('solventName').value=s.solventName||'';$('approximate').checked=!!s.approximate;$('densityPreset').value='';}
function renderTargetOptions(){let q=$('targetSearch').value.trim().toLowerCase(),s=current(),vars=group().vars.filter(v=>(v.label+' '+v.id+' '+(v.context||'')).toLowerCase().includes(q));let chosen=group().vars.find(v=>v.id===s.target);if(chosen&&!vars.includes(chosen))vars.unshift(chosen);$('answerTarget').innerHTML='<option value="">Choose a final answer (optional)</option>'+vars.map(v=>`<option value="${v.id}" ${s.target===v.id?'selected':''}>${esc(v.label)}</option>`).join('');$('answerTarget').value=s.target||'';$('targetMatches').textContent=vars.length+' matching quantities'+(chosen&&q&&!chosen.label.toLowerCase().includes(q)?' (including your selected target)':'');}
function gatherChemistry(inputs,inputPrecision,invalid){let formulas={};for(const [kind,id] of [['solute','solution_M'],['gas','gas_M']]){let info=$(kind+'Info'),raw=current().chemical?.[kind]||'';info.textContent='';if(topic!=='all'||!raw.trim())continue;try{let f=ChemFormula.parse(raw);info.textContent=f.mass.toFixed(Math.max(0,-f.precision.p))+' g/mol · '+Object.entries(f.counts).map(([e,n])=>e+': '+n).join(', ');if(inputs[id]!==undefined){if(Math.abs(inputs[id]-f.mass)>1e-6+1e-3*f.mass)invalid.push('Entered molar mass conflicts with '+raw+'. Clear the numeric molar mass to use the formula.');}else{inputs[id]=f.mass;inputPrecision[id]=f.precision;formulas[id]=f;}}catch(e){info.textContent=e.message;invalid.push(kind+' formula: '+e.message);}}return formulas;}
let answerPlans=[];
function updateGoal(){let target=current().target,name=id=>group().vars.find(v=>v.id===id)?.label||id;if(!target){$('goalStatus').innerHTML='<p class="muted">Select a final answer above to see what is still needed.</p>';answerPlans=[];return;}const warnings=result.issues.length||result.inputIssues?.length?'<p class="issue">Resolve invalid or conflicting inputs before using this answer.</p>':'';if(result.values[target]!==undefined){$('goalStatus').innerHTML=`<p><b>${esc(name(target))}</b></p><div class="answer-value">${esc(displayed(target,result.values[target]))}</div>${warnings}<p class="muted">${result.trails[target]?'Your current inputs are enough.':'You supplied this value.'}</p>${result.trails[target]?`<button data-answer-trail="${target}">Show calculation</button>`:''}`;answerPlans=[];return;}
answerPlans=ChemPlanner.plan(group(),result.values,target);$('goalStatus').innerHTML=`<p><b>${esc(name(target))}</b></p>${warnings}<p class="muted">Alternative sets of additional values; choose any one route.</p>`+answerPlans.map((p,i)=>`<div class="answer-route"><b>Route ${i+1} · ${p.missing.length} more ${p.missing.length===1?'value':'values'}</b><ul>${p.missing.map(id=>`<li>${esc(name(id))}${/_M$/.test(id)?' (or enter its chemical formula)':''}</li>`).join('')}</ul><details><summary>How this reaches your answer</summary>${p.steps.map(s=>`<p class="muted">${esc(s.label)} → ${esc(name(s.id))}</p>`).join('')}</details><button data-focus-plan="${i}">Show these inputs</button></div>`).join('')+'<p class="muted">Routes follow the available rearrangements. Numeric inputs must still be physically valid; zero or degenerate cases can block a route. Up to five minimal routes are shown.</p>';if(!answerPlans.length)$('goalStatus').innerHTML+='<p>No route is available in this equation library.</p>';}
$('answerTarget').onchange=()=>{current().target=$('answerTarget').value;current().focus=null;updateGoal();filterFields();};
for(const kind of ['solute','gas'])$(kind+'Formula').oninput=()=>{current().chemical||={};current().chemical[kind]=$(kind+'Formula').value;update();};
$('goalStatus').onclick=e=>{if(e.target.dataset.answerTrail){$('fields').onclick({target:{dataset:{trail:e.target.dataset.answerTrail}}});}if(e.target.dataset.focusPlan!==undefined){let p=answerPlans[Number(e.target.dataset.focusPlan)];if(p){current().focus=new Set([...p.missing,current().target,...p.steps.map(s=>s.id)]);$('search').value='';$('relevant').checked=false;filterFields();$('fields').scrollIntoView?.({behavior:'smooth',block:'start'});}}};
$('targetSearch').oninput=()=>{renderTargetOptions();const raw=$('targetSearch').value.trim();const match=group().vars.find(v=>v.label===raw);if(match){current().target=match.id;current().focus=null;updateGoal();filterFields();$('targetMatches').textContent='Answer selected. Missing inputs appear automatically below.';}else if(!raw){current().target='';current().focus=null;updateGoal();filterFields();$('targetMatches').textContent='Optional: choose an answer to see what’s missing.';}else $('targetMatches').textContent='Choose a matching quantity from the dropdown.';};
$('solventName').oninput=()=>{current().solventName=$('solventName').value;$('densityPreset').value='';};
$('densityPreset').onchange=()=>{let preset=$('densityPreset').value;if(!preset)return;let s=current();s.solventName='Water';$('solventName').value='Water';s.inputs.solution_solventDensity=preset==='classroom'?'1.00':'0.99705';s.selected.solution_solventDensity='g/mL';if(s.precision)delete s.precision.solution_solventDensity;if(s.exact)delete s.exact.solution_solventDensity;update();};
$('approximate').onchange=()=>{current().approximate=$('approximate').checked;render();};
const originalSetupGoals=setupGoals;
setupGoals=function(){originalSetupGoals();$('targetQuantities').innerHTML=group().vars.map(v=>`<option value="${esc(v.label)}"></option>`).join('');$('targetSearch').value=group().vars.find(v=>v.id===current().target)?.label||'';$('targetMatches').textContent=current().target?'Answer selected. Missing inputs appear automatically below.':'Optional: choose an answer to see what’s missing.';};
const originalSearch=$('search').oninput;
$('search').oninput=()=>{const match=group().vars.find(v=>v.label===$('search').value.trim());if(match){current().added||=[];if(!current().added.includes(match.id))current().added.push(match.id);$('search').value='';filterFields();$('input-'+match.id).focus?.();$('field-'+match.id).scrollIntoView?.({behavior:'smooth',block:'nearest'});}else originalSearch();};
const originalReset=$('reset').onclick;
$('reset').onclick=()=>{$('search').value='';$('targetSearch').value='';originalReset();};
const originalUpdateGoal=updateGoal;
updateGoal=function(){originalUpdateGoal();const host=$('goalStatus');if(answerPlans.length>1){const html=host.innerHTML,start=html.indexOf('<div class="answer-route">'),second=html.indexOf('<div class="answer-route">',start+1),end=html.lastIndexOf('<p class="muted">Routes follow');if(second>=0&&end>=0)host.innerHTML=html.slice(0,second)+'<details class="alternative-routes"><summary>Other ways to reach this answer</summary>'+html.slice(second,end)+'</details>'+html.slice(end);}if(!current().target&&Object.keys(result.values).length)host.innerHTML='<p class="muted">Your calculated values appear alongside your inputs. Choose an answer above for focused guidance.</p>';};
render();
