const assert=require('node:assert/strict'),E=require('./engine.js');require('./sciences.js');require('./expanded.js');require('./ap-library.js');const T=require('./math-tools.js'),Q=require('./precision.js');
const near=(a,b,t=1e-7)=>assert.ok(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`),solve=x=>E.solve('all',x);
near(E.parse('-x^2',{x:3}).value,-9);near(E.parse('2^-2').value,.25);near(E.parse('2^3^2').value,512);near(Q.evaluate('-x^2',{x:3},{x:{value:3,p:-2}}).value,-9);
near(solve({rotation_I:2,rotation_alpha:3,rotation_omega:4}).values.rotation_torque,6);
near(solve({rotation_I:2,rotation_alpha:3,rotation_omega:4}).values.rotation_K,16);
near(solve({lever_F:10,lever_r:2,lever_angle:Math.PI/2}).values.lever_torque,20);
near(solve({flow_A1:2,flow_v1:3,flow_A2:1}).values.flow_v2,6);
near(solve({thermophysics_Q:100,thermophysics_W:-20}).values.thermophysics_Uchange,80);
near(solve({electric_q1:1e-6,electric_q2:-1e-6,electric_r:1}).values.electric_energy,-.0089875517923);
near(solve({rparallel_one:100,rparallel_two:100}).values.rparallel_equivalent,50);
near(solve({rc_R:1000,rc_C:.001,rc_t:1,rc_initial:1}).values.rc_charge,Math.exp(-1));
near(solve({refraction_n1:1,refraction_n2:1.5,refraction_theta1:Math.PI/6}).values.refraction_theta2,Math.asin(1/3));
near(solve({sample_n:25,sample_s:10}).values.sample_SE,2);
near(solve({binomial_n:10,binomial_p:.5,binomial_x:3}).values.binomial_probability,120/1024);near(solve({binomial_n:10,binomial_p:0,binomial_x:0}).values.binomial_probability,1);near(solve({binomial_n:10,binomial_p:1,binomial_x:10}).values.binomial_probability,1);
near(solve({normal_x:110,normal_mean:100,normal_sd:10}).values.normal_lower,.841344746,2e-7);
near(solve({normal_lower:.975}).values.normal_z,1.959963984,2e-6);
near(solve({proportion_n:100,proportion_successes:60,proportion_p0:.5}).values.proportion_z,2);
near(solve({macro_C:100,macro_I:20,macro_G:30,macro_X:10,macro_M:15}).values.macro_GDP,145);
near(solve({multiplier_MPC:.8,multiplier_changeG:100}).values.multiplier_outputG,500);
near(solve({waterpotential_pressure:0,waterpotential_i:1,waterpotential_c:.1,waterpotential_T:298.15}).values.waterpotential_total,-.1*.082057366*298.15);
near(solve({geometrysphere_r:1}).values.geometrysphere_volume,4*Math.PI/3);
near(solve({acid_Ka:1e-5,acid_Kw:1e-14}).values.acid_Kb,1e-9);
near(solve({series_first:2,series_ratio:.5,series_n:3}).values.series_sum,3.5);assert.equal(solve({series_first:2,series_ratio:2,series_n:3}).values.series_infinite,undefined);
assert.equal(E.valid('closedpipe_harmonic',2,'all'),false);assert.equal(E.valid('regression_r',1.1,'all'),false);
const stats=T.sample([1,2,3,4],[3,5,7,9]);near(stats.sample_mean,2.5);near(stats.sample_s,Math.sqrt(5/3));near(stats.regression_b,2);near(stats.regression_a,1);near(stats.regression_r,1);
near(T.chi([10,20],[15,15]).chisquare_chi,10/3);near(T.diversity([10,10]).diversity_index,.5);near(T.distribution([0,1],[.5,.5]).distribution_sd,.5);
near(T.at('x^3',2).function_derivative,12);near(T.at('-x^2',2).function_derivative,-4);near(T.integral('x^2',0,3).function_integral,9);near(T.integral('sin(x)',0,Math.PI).function_integral,2);
assert.throws(()=>T.at('abs(x)',0));assert.throws(()=>T.integral('1/x',-1,1));assert.throws(()=>T.sample([1,2],[3]));assert.throws(()=>T.distribution([1,2],[.5,.6]));assert.throws(()=>T.f('process.exit()',1));
const ids=new Set(E.groups.all.vars.map(v=>v.id));assert.equal(ids.size,E.groups.all.vars.length);for(const eq of E.groups.all.eqs)for(const [id,expr]of Object.entries(eq.forms)){assert.ok(ids.has(id));for(const dep of E.parse(expr).deps)assert.ok(ids.has(dep),dep);}
for(const v of E.groups.all.vars)assert.ok(E.units[v.type],v.type);
console.log(`Passed AP expansion: ${ids.size} quantities, ${E.groups.all.eqs.length} relationships; mechanics, E&M, thermo, optics, chemistry, statistics, economics, geometry, safe trig, data and numeric calculus.`);
